[gravity]
#host = "0.0.0.0:44444"
host = "0.0.0.0"
port = 32803
pingInterval = 10
maxPingsOutstanding = 3
maxReconnects = -1

[adapter]
adapter_id = "native_adapter"
adapter_name = "Native Adapter"
state_store = "./statestore"

[source]
config = "./settings/sources.json"
