[gravity]
#host = "0.0.0.0:44444"
domain = "gravity"
host = "0.0.0.0"
port = 32803
pingInterval = 10
maxPingsOutstanding = 3
maxReconnects = -1

[adapter]
adapterID = "native_adapter"
adapterNameame = "Native Adapter"
stateStore = "./statestore"

# Authentication
appID = "anonymous"
accessKey = ""

[source]
config = "./settings/sources.json"
